const mongoose = require("mongoose");
const Doctor = require("./models/Doctor");

mongoose.connect("mongodb+srv://imhimanshu1605:FOtG3aFR1MNHmXXT@data.zeeqsnj.mongodb.net/?retryWrites=true&w=majority&appName=data", {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

const dummyDoctors = [
  // Mumbai (3)
  {
    name: "Dr. Asha Meena",
    profession: "Dermatologist",
    experience: "7 years",
    location: "Mumbai",
    fee: 500,
    image: "https://randomuser.me/api/portraits/women/47.jpg",
    rating: 4.5,
    stories: "102 patient stories",
    isAd: true,
    available: true,
  },
  {
    name: "Dr. Priya Nair",
    profession: "Dermatologist",
    experience: "6 years",
    location: "Mumbai",
    fee: 520,
    image: "https://randomuser.me/api/portraits/women/32.jpg",
    rating: 4.6,
    stories: "98 patient stories",
    isAd: false,
    available: true,
  },
  {
    name: "Dr. Kunal Bhatia",
    profession: "Dentist",
    experience: "5 years",
    location: "Mumbai",
    fee: 400,
    image: "https://randomuser.me/api/portraits/men/56.jpg",
    rating: 4.2,
    stories: "60 patient stories",
    isAd: false,
    available: true,
  },

  // Delhi (3)
  {
    name: "Dr. Ramesh Sharma",
    profession: "Cardiologist",
    experience: "10 years",
    location: "Delhi",
    fee: 700,
    image: "https://randomuser.me/api/portraits/men/46.jpg",
    rating: 4.9,
    stories: "200 patient stories",
    isAd: false,
    available: true,
  },
  {
    name: "Dr. Anjali Verma",
    profession: "Pediatrician",
    experience: "8 years",
    location: "Delhi",
    fee: 550,
    image: "https://randomuser.me/api/portraits/women/28.jpg",
    rating: 4.7,
    stories: "115 patient stories",
    isAd: true,
    available: true,
  },
  {
    name: "Dr. Karan Gupta",
    profession: "General Physician",
    experience: "6 years",
    location: "Delhi",
    fee: 450,
    image: "https://randomuser.me/api/portraits/men/35.jpg",
    rating: 4.3,
    stories: "95 patient stories",
    isAd: false,
    available: true,
  },

  // Chennai (3)
  {
    name: "Dr. Ankit Gupta",
    profession: "Orthopedic",
    experience: "8 years",
    location: "Chennai",
    fee: 600,
    image: "https://randomuser.me/api/portraits/men/33.jpg",
    rating: 4.6,
    stories: "120 patient stories",
    isAd: false,
    available: true,
  },
  {
    name: "Dr. Lavanya Iyer",
    profession: "Gynecologist",
    experience: "9 years",
    location: "Chennai",
    fee: 580,
    image: "https://randomuser.me/api/portraits/women/18.jpg",
    rating: 4.5,
    stories: "108 patient stories",
    isAd: false,
    available: true,
  },
  {
    name: "Dr. Suresh Kumar",
    profession: "ENT Specialist",
    experience: "11 years",
    location: "Chennai",
    fee: 490,
    image: "https://randomuser.me/api/portraits/men/66.jpg",
    rating: 4.7,
    stories: "123 patient stories",
    isAd: true,
    available: true,
  },

  // Pune (3)
  {
    name: "Dr. Meera Sinha",
    profession: "Gynecologist",
    experience: "12 years",
    location: "Pune",
    fee: 550,
    image: "https://randomuser.me/api/portraits/women/25.jpg",
    rating: 4.8,
    stories: "180 patient stories",
    isAd: true,
    available: true,
  },
  {
    name: "Dr. Ravi Joshi",
    profession: "Neurologist",
    experience: "14 years",
    location: "Pune",
    fee: 880,
    image: "https://randomuser.me/api/portraits/men/19.jpg",
    rating: 4.6,
    stories: "160 patient stories",
    isAd: false,
    available: false,
  },
  {
    name: "Dr. Riya Deshmukh",
    profession: "Psychiatrist",
    experience: "10 years",
    location: "Pune",
    fee: 640,
    image: "https://randomuser.me/api/portraits/women/40.jpg",
    rating: 4.5,
    stories: "140 patient stories",
    isAd: true,
    available: true,
  },

  // Hyderabad (3)
  {
    name: "Dr. Arjun Reddy",
    profession: "General Physician",
    experience: "9 years",
    location: "Hyderabad",
    fee: 300,
    image: "https://randomuser.me/api/portraits/men/41.jpg",
    rating: 4.2,
    stories: "75 patient stories",
    isAd: true,
    available: true,
  },
  {
    name: "Dr. Sneha Rao",
    profession: "Dermatologist",
    experience: "6 years",
    location: "Hyderabad",
    fee: 420,
    image: "https://randomuser.me/api/portraits/women/39.jpg",
    rating: 4.4,
    stories: "80 patient stories",
    isAd: false,
    available: true,
  },
  {
    name: "Dr. Manish Verma",
    profession: "Dentist",
    experience: "5 years",
    location: "Hyderabad",
    fee: 390,
    image: "https://randomuser.me/api/portraits/men/21.jpg",
    rating: 4.1,
    stories: "65 patient stories",
    isAd: false,
    available: true,
  },

  // Kolkata (3)
  {
    name: "Dr. Neha Joshi",
    profession: "Psychiatrist",
    experience: "11 years",
    location: "Kolkata",
    fee: 650,
    image: "https://randomuser.me/api/portraits/women/45.jpg",
    rating: 4.6,
    stories: "130 patient stories",
    isAd: true,
    available: false,
  },
  {
    name: "Dr. Abhay Sen",
    profession: "Neurologist",
    experience: "13 years",
    location: "Kolkata",
    fee: 720,
    image: "https://randomuser.me/api/portraits/men/52.jpg",
    rating: 4.7,
    stories: "150 patient stories",
    isAd: false,
    available: true,
  },
  {
    name: "Dr. Rachna Pal",
    profession: "Pediatrician",
    experience: "7 years",
    location: "Kolkata",
    fee: 500,
    image: "https://randomuser.me/api/portraits/women/34.jpg",
    rating: 4.3,
    stories: "90 patient stories",
    isAd: false,
    available: true,
  },

  // Jaipur (3)
  {
    name: "Dr. Rajeev Menon",
    profession: "Dentist",
    experience: "4 years",
    location: "Jaipur",
    fee: 350,
    image: "https://randomuser.me/api/portraits/men/12.jpg",
    rating: 4.3,
    stories: "60 patient stories",
    isAd: false,
    available: true,
  },
  {
    name: "Dr. Sheetal Kaur",
    profession: "Cardiologist",
    experience: "9 years",
    location: "Jaipur",
    fee: 750,
    image: "https://randomuser.me/api/portraits/women/22.jpg",
    rating: 4.8,
    stories: "150 patient stories",
    isAd: true,
    available: true,
  },
  {
    name: "Dr. Ajay Rathore",
    profession: "Orthopedic",
    experience: "6 years",
    location: "Jaipur",
    fee: 620,
    image: "https://randomuser.me/api/portraits/men/24.jpg",
    rating: 4.5,
    stories: "100 patient stories",
    isAd: false,
    available: true,
  },
];

async function seedDB() {
  try {
    await Doctor.deleteMany({});
    await Doctor.insertMany(dummyDoctors);
    console.log("✅ Doctors seeded successfully");
  } catch (err) {
    console.error("❌ Seeding error:", err);
  } finally {
    mongoose.connection.close();
  }
}

seedDB();
